meta_product_name: "Buddy"
meta_title: "Buddy - Le quotidien devient easy !"
meta_description: "Remets toi sur les rails avec Buddy !"
meta_image: "Buddywallpaper.png" # should exist in `app/assets/images/`
twitter_account: "@Joupsie"   # required for Twitter Cards
